import { Icon } from "@iconify/react";
import { Form } from "antd";
import { useForm } from "antd/lib/form/Form";
import Head from "next/head";
import React, { useState } from "react";

function SignUp() {
  const { form } = useForm();

  return (
    <>
      <div>
        <Head>
          <title>DNED / NNSS Payments | SignUp</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <div className="h-full min-h-screen flex flex-col w-full">
        <WebNavigation viewHeaderonAuth={true} />
        <div className="h-screen min-h-screen w-full flex items-center justify-center">
          <div className="w-full max-w-md p-6 bg-[#1f1839] flex items-center justify-center flex-col">
            <div>
              <Form form={form} layout="vertical" className="w-full"></Form>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default SignUp;
