import { Icon } from "@iconify/react";
import { Form } from "antd";
import { useForm } from "antd/lib/form/Form";
import Head from "next/head";
import React, { useState } from "react";
import { WebNavigation } from "../components/navigation/nav";
import { CustomItem, CustomInput } from "../styles/styled";
import { DefaultButton } from "../components/customButton/defaultButton";

function Forgotpassword() {
  const { form } = useForm();

  return (
    <>
      <div>
        <Head>
          <title>DNED / NNSS Payments | SignIn</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <div className="h-full min-h-screen flex items-center justify-center flex-col w-full">
        <WebNavigation viewHeaderonAuth={true} />
        <div className="h-full w-full flex items-center justify-center">
          <div className="w-full max-w-lg p-6 bg-primary h-64 flex items-center justify-center flex-col">
            <div className="w-full max-w-sm">
              <Form form={form} layout="vertical" className="w-full">
                <div className="w-full flex flex-col gap-y-8 gap-x-4">
                  <CustomItem
                    name="schoolmail"
                    rules={[
                      {
                        required: false,
                        message: "please enter school email",
                      },
                    ]}
                  >
                    <CustomInput
                      name="schoolemail"
                      type="email"
                      placeholder="school email address"
                    />
                  </CustomItem>

                  <DefaultButton className="w-full bg-secondary text-primary py-3 px-4 rounded-md font-montserrat font-semibold tracking-[0.06em]">
                    Send password reset mail
                  </DefaultButton>
                </div>
              </Form>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default Forgotpassword;
