import { Icon } from "@iconify/react";
import Head from "next/head";
import { DefaultButton } from "../components/customButton/defaultButton";
import WebLayout from "../components/layout/layout";
import { SliderHome } from "../components/slider/sliderHome";

export default function SelectSchool() {
  return (
    <div>
      <Head>
        <title>DNED / NNSS Payments | Select School</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WebLayout>
        <div className="h-full w-full bg-white px-6 py-4 flex-col gap-x-4 gap-y-6 items-center flex justify-center">
          {/* heading and layout changer */}
          <div className="w-full max-w-[72rem] p-4 bg-primary mt-6">
            <div className="flex items-center justify-between w-full">
              <h3 className="font-inter capitalize tracking-[0.06em] text-secondary leading-[21.78px] font-bold text-lg">
                Select NNSS{" "}
                <span className="font-normal lowercase text-white tracking-normal font-montserrat text-base">
                  school of choice
                </span>
              </h3>

              <DefaultButton className="text-white flex items-center gap-x-2 font-montserrat text-base">
                <Icon
                  icon="ant-design:layout-filled"
                  className="text-secondary"
                  width="30"
                  height="30"
                />
                Change layout
              </DefaultButton>
            </div>
          </div>
          {/* heading and layout changer */}

          {/* Select schoools */}
          <div className="w-full max-w-[72rem] p-4 bg-yellow-500"></div>
          {/* Select schoools */}
        </div>
      </WebLayout>
    </div>
  );
}
