import { Tabs } from "antd";
import Head from "next/head";
import React, { useState } from "react";
import DashboardLayout from "../../components/layout/dashboardLayout";
import MakePayment from "../../components/payment/makepayment";
import PaymentHistory from "../../components/payment/paymenthistory";
import { CustomTabs } from "../../styles/styled";

function Payment() {
  const onChange = (key) => {
    console.log(key);
  };

  return (
    <>
      <div>
        <Head>
          <title>NNSS Payments | Payment</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <DashboardLayout>
        <div className="mt-4">
          <h2 className="font-semibold text-2xl font-inter tracking-[0.06em] text-[#1f1839]">
            Payment Status
          </h2>
          <div className="w-full mt-4 border-t-4 border-b-4 border-primary bg-white shadow-md max-w-4xl p-4">
            <CustomTabs
              defaultActiveKey="payment history"
              onChange={onChange}
              tabBarGutter={30}
              items={[
                {
                  label: "Online Payment",
                  key: "online Payment",
                  children: <MakePayment />,
                },
                {
                  label: "Payment History",
                  key: "payment history",
                  children: <PaymentHistory />,
                },
              ]}
            />
          </div>
        </div>
      </DashboardLayout>
    </>
  );
}

export default Payment;
