import Head from "next/head";
import React from "react";
import DashboardLayout from "../../components/layout/dashboardLayout";

function Payment() {
  return (
    <>
      <div>
        <Head>
          <title>NNSS Payments | Payment</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <DashboardLayout>
        hello payment here
      </DashboardLayout>
    </>
  );
}

export default Payment;
